"use strict";

const mongoose = require("mongoose");
const { COMPLAINT_STATUS, COMPLAINT_PRIORITY } = require("../../common/constants");

/**
 * Complaint — helpdesk ticket raised by a resident.
 * Lives in mysociety_operations.complaints
 *
 * Key design decisions:
 *  - ticketId is unique, human-readable (TKT-XXXXXXX), generated via atomic counter
 *  - assignedToType distinguishes internal_staff vs vendor assignments
 *  - SLA fields enable configurable escalation without hardcoding
 *  - Full lifecycle timestamps: assigned, resolved, closed, reopened
 *  - version field enables optimistic concurrency control
 */
const complaintSchema = new mongoose.Schema(
    {
        // ── Identification ───────────────────────────────────────────────────────
        ticketId: {
            type: String,
            unique: true,
            index: true,
            // Generated by ComplaintService using atomic counter — never set by client
        },

        // ── Multi-Tenant Isolation ────────────────────────────────────────────
        societyId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Society",
            required: [true, "societyId is required"],
        },

        // ── Resident / Flat Context ───────────────────────────────────────────
        flatId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Flat",
            required: [true, "flatId is required"],
        },
        raisedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
            required: [true, "raisedBy is required"],
        },

        // ── Complaint Content ─────────────────────────────────────────────────
        category: {
            type: String,
            required: [true, "Category is required"],
            trim: true, // e.g. "Plumbing", "Electrical", "Common Area"
        },
        description: {
            type: String,
            required: [true, "Description is required"],
            trim: true,
        },
        attachments: {
            type: [String], // Array of URLs/paths
            default: [],
        },

        // ── Status & Priority ─────────────────────────────────────────────────
        status: {
            type: String,
            enum: Object.values(COMPLAINT_STATUS),
            default: COMPLAINT_STATUS.OPEN,
        },
        priority: {
            type: String,
            enum: Object.values(COMPLAINT_PRIORITY),
            default: COMPLAINT_PRIORITY.MEDIUM,
        },

        // ── Assignment ────────────────────────────────────────────────────────
        assignedToType: {
            type: String,
            enum: ["internal_staff", "vendor", null],
            default: null,
        },
        assignedStaffId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Staff",
            default: null,
        },
        assignedVendorId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Vendor",
            default: null,
        },
        assignedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
            default: null,
        },
        assignedAt: {
            type: Date,
            default: null,
        },

        // ── Resolution ────────────────────────────────────────────────────────
        resolvedAt: {
            type: Date,
            default: null,
        },
        resolvedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
            default: null,
        },
        resolutionRemarks: {
            type: String,
            trim: true,
            default: null,
        },

        // ── Resident Confirmation (CLOSED) ────────────────────────────────────
        closedAt: {
            type: Date,
            default: null,
        },
        closedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
            default: null,
        },

        // ── Reopen ────────────────────────────────────────────────────────────
        reopenedAt: {
            type: Date,
            default: null,
        },
        reopenedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
            default: null,
        },
        reopeningRemarks: {
            type: String,
            trim: true,
            default: null,
        },
        reopenCount: {
            type: Number,
            default: 0,
        },

        // ── SLA ───────────────────────────────────────────────────────────────
        sla: {
            durationHours: { type: Number, default: null },    // Configurable SLA window
            startedAt:     { type: Date,   default: null },    // When SLA timer started
            dueAt:         { type: Date,   default: null },    // Calculated deadline
            status: {
                type: String,
                enum: ["within", "breached", "resolved_within", null],
                default: null,
            },
        },

        // ── Escalation ────────────────────────────────────────────────────────
        escalation: {
            isEscalated:     { type: Boolean, default: false },
            escalatedAt:     { type: Date,    default: null },
            escalationLevel: { type: Number,  default: 0 },
            escalationReason:{ type: String,  default: null },
        },

        // ── Concurrency Control ────────────────────────────────────────────────
        version: {
            type: Number,
            default: 0,
        },
    },
    { timestamps: true }
);

// ── Indexes ───────────────────────────────────────────────────────────────────
// Query: Admin views all society complaints (with status filter, sorted by newest)
complaintSchema.index({ societyId: 1, status: 1, createdAt: -1 });

// Query: Resident views their own complaints
complaintSchema.index({ societyId: 1, raisedBy: 1, createdAt: -1 });

// Query: Admin assigns to / views by staff
complaintSchema.index({ societyId: 1, assignedStaffId: 1, status: 1 });

// Query: Vendor portal — complaints assigned to a vendor
complaintSchema.index({ societyId: 1, assignedVendorId: 1, status: 1 });

// Query: SLA escalation scheduler — find overdue open/in-progress tickets
complaintSchema.index({ societyId: 1, "sla.dueAt": 1, status: 1 });

// Query: By flat
complaintSchema.index({ societyId: 1, flatId: 1 });

module.exports = complaintSchema;
