"use strict";

const mongoose = require("mongoose");
const { QR_PASS_TYPE, QR_PASS_STATUS } = require("../../common/constants");

/**
 * QRDigitalPass — Digital QR passes generated by residents for visitors.
 */
const qrDigitalPassSchema = new mongoose.Schema(
    {
        societyId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Society",
            required: [true, "societyId is required"],
        },
        flatId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Flat",
            required: [true, "flatId is required"],
        },
        residentId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
            required: [true, "residentId is required"],
        },
        visitorName: {
            type: String,
            required: [true, "Visitor name is required"],
            trim: true,
        },
        visitorMobile: {
            type: String,
            trim: true,
        },
        type: {
            type: String,
            enum: Object.values(QR_PASS_TYPE),
            required: [true, "QR pass type is required"],
        },
        validFrom: {
            type: Date,
            required: [true, "validFrom is required"],
        },
        validTo: {
            type: Date,
            required: [true, "validTo is required"],
        },
        validDays: {
            type: [String], // e.g., ["Monday", "Tuesday"]
            default: [],
        },
        timeWindowStart: {
            type: String, // e.g., "18:00"
        },
        timeWindowEnd: {
            type: String, // e.g., "22:00"
        },
        isUsed: {
            type: Boolean,
            default: false,
        },
        status: {
            type: String,
            enum: Object.values(QR_PASS_STATUS),
            default: QR_PASS_STATUS.ACTIVE,
        },
        passCode: {
            type: String,
            required: true,
            unique: true, // Unique string embedded in QR
        },
    },
    { timestamps: true }
);

qrDigitalPassSchema.index({ societyId: 1, passCode: 1 });
qrDigitalPassSchema.index({ flatId: 1, residentId: 1 });

module.exports = qrDigitalPassSchema;
