"use strict";

const { ROLES } = require("./constants");

const BILLING_PERMISSIONS = Object.freeze({
    // Charge Heads
    CHARGE_HEAD_VIEW: "BILLING.CHARGE_HEAD.VIEW",
    CHARGE_HEAD_CREATE: "BILLING.CHARGE_HEAD.CREATE",
    CHARGE_HEAD_UPDATE: "BILLING.CHARGE_HEAD.UPDATE",
    CHARGE_HEAD_APPROVE: "BILLING.CHARGE_HEAD.APPROVE",

    // Billing Config
    CONFIG_VIEW: "BILLING.CONFIG.VIEW",
    CONFIG_CREATE: "BILLING.CONFIG.CREATE",
    CONFIG_UPDATE: "BILLING.CONFIG.UPDATE",
    CONFIG_APPROVE: "BILLING.CONFIG.APPROVE",

    // Invoices
    INVOICE_VIEW: "BILLING.INVOICE.VIEW",
    INVOICE_GENERATE: "BILLING.INVOICE.GENERATE",
    INVOICE_UPDATE: "BILLING.INVOICE.UPDATE",

    // Payments
    PAYMENT_VIEW: "BILLING.PAYMENT.VIEW",
    PAYMENT_OFFLINE_CREATE: "BILLING.PAYMENT.OFFLINE_CREATE",
    PAYMENT_ONLINE_VIEW: "BILLING.PAYMENT.ONLINE_VIEW",

    // Credit Notes
    CREDIT_NOTE_CREATE: "BILLING.CREDIT_NOTE.CREATE",
    CREDIT_NOTE_APPROVE: "BILLING.CREDIT_NOTE.APPROVE",

    // Discounts
    DISCOUNT_CREATE: "BILLING.DISCOUNT.CREATE",
    DISCOUNT_APPROVE: "BILLING.DISCOUNT.APPROVE",

    // Reconciliation
    RECONCILIATION_VIEW: "BILLING.RECONCILIATION.VIEW",
    RECONCILIATION_RECONCILE: "BILLING.RECONCILIATION.RECONCILE",

    // Journal Vouchers
    JOURNAL_VOUCHER_CREATE: "BILLING.JOURNAL_VOUCHER.CREATE",
    JOURNAL_VOUCHER_UPDATE: "BILLING.JOURNAL_VOUCHER.UPDATE",
    JOURNAL_VOUCHER_DELETE: "BILLING.JOURNAL_VOUCHER.DELETE",
    JOURNAL_VOUCHER_APPROVE: "BILLING.JOURNAL_VOUCHER.APPROVE",

    // Vendor Payments
    VENDOR_PAYMENT_CREATE: "BILLING.VENDOR_PAYMENT.CREATE",
    VENDOR_PAYMENT_APPROVE: "BILLING.VENDOR_PAYMENT.APPROVE",

    // Budget
    BUDGET_VIEW: "BILLING.BUDGET.VIEW",
    BUDGET_CREATE: "BILLING.BUDGET.CREATE",
    BUDGET_APPROVE: "BILLING.BUDGET.APPROVE",

    // Reports & Ledgers
    REPORT_VIEW: "BILLING.REPORT.VIEW",
    LEDGER_VIEW: "BILLING.LEDGER.VIEW",
    AUDIT_LOG_VIEW: "BILLING.AUDIT_LOG.VIEW",

    // Resident Own-Resource Scope
    OWN_INVOICE_VIEW: "BILLING.OWN_INVOICE.VIEW",
    OWN_PAYMENT_CREATE: "BILLING.OWN_PAYMENT.CREATE",
    OWN_PAYMENT_VIEW: "BILLING.OWN_PAYMENT.VIEW",
    OWN_LEDGER_VIEW: "BILLING.OWN_LEDGER.VIEW",

    // Fines, Interest & Arrears (Dunning)
    DUNNING_VIEW: "BILLING.DUNNING.VIEW",
    DUNNING_RULE_CREATE: "BILLING.DUNNING.RULE_CREATE",
    DUNNING_RULE_APPROVE: "BILLING.DUNNING.RULE_APPROVE",
    DUNNING_WAIVER_CREATE: "BILLING.DUNNING.WAIVER_CREATE",
    DUNNING_REMINDER_SEND: "BILLING.DUNNING.REMINDER_SEND",

    // Advance Accounts
    BILLING_ADVANCE_VIEW_ALL: "BILLING.ADVANCE.VIEW_ALL",
    BILLING_ADVANCE_VIEW_OWN: "BILLING.ADVANCE.VIEW_OWN",
    BILLING_ADVANCE_CREATE: "BILLING.ADVANCE.CREATE",
    BILLING_ADVANCE_ALLOCATE: "BILLING.ADVANCE.ALLOCATE",
    BILLING_ADVANCE_REVERSE_ALLOCATION: "BILLING.ADVANCE.REVERSE_ALLOCATION",
    BILLING_ADVANCE_ADJUST: "BILLING.ADVANCE.ADJUST",
    BILLING_ADVANCE_REFUND: "BILLING.ADVANCE.REFUND",
    BILLING_ADVANCE_APPROVE_REFUND: "BILLING.ADVANCE.APPROVE_REFUND",

    // Security Deposits
    BILLING_DEPOSIT_VIEW_ALL: "BILLING.DEPOSIT.VIEW_ALL",
    BILLING_DEPOSIT_VIEW_OWN: "BILLING.DEPOSIT.VIEW_OWN",
    BILLING_DEPOSIT_CONFIGURE: "BILLING.DEPOSIT.CONFIGURE",
    BILLING_DEPOSIT_CREATE: "BILLING.DEPOSIT.CREATE",
    BILLING_DEPOSIT_ADJUST: "BILLING.DEPOSIT.ADJUST",
    BILLING_DEPOSIT_APPROVE_ADJUSTMENT: "BILLING.DEPOSIT.APPROVE_ADJUSTMENT",
    BILLING_DEPOSIT_REFUND: "BILLING.DEPOSIT.REFUND",
    BILLING_DEPOSIT_APPROVE_REFUND: "BILLING.DEPOSIT.APPROVE_REFUND",

    // Accounting & Audit Granular
    ACCOUNTING_LEDGER_VIEW: "ACCOUNTING.LEDGER.VIEW",
    ACCOUNTING_TRANSACTION_VIEW: "ACCOUNTING.TRANSACTION.VIEW",
    BANKING_ACCOUNT_VIEW: "BANKING.ACCOUNT.VIEW",
    REPORTS_BILLING_VIEW: "REPORTS.BILLING.VIEW",
    REPORTS_FINANCIAL_VIEW: "REPORTS.FINANCIAL.VIEW",
    AUDIT_VIEW: "AUDIT.VIEW",
});

const BILLING_ROLE_MATRIX = Object.freeze({
    // 1. Committee Admin (admin / committee_admin / committee_member)
    [ROLES.ADMIN]: [
        BILLING_PERMISSIONS.CHARGE_HEAD_VIEW,
        BILLING_PERMISSIONS.CHARGE_HEAD_CREATE,
        BILLING_PERMISSIONS.CHARGE_HEAD_UPDATE,
        BILLING_PERMISSIONS.CHARGE_HEAD_APPROVE,
        BILLING_PERMISSIONS.CONFIG_VIEW,
        BILLING_PERMISSIONS.CONFIG_CREATE,
        BILLING_PERMISSIONS.CONFIG_UPDATE,
        BILLING_PERMISSIONS.CONFIG_APPROVE,
        BILLING_PERMISSIONS.INVOICE_VIEW,
        BILLING_PERMISSIONS.INVOICE_GENERATE,
        BILLING_PERMISSIONS.INVOICE_UPDATE,
        BILLING_PERMISSIONS.PAYMENT_VIEW,
        BILLING_PERMISSIONS.PAYMENT_OFFLINE_CREATE,
        BILLING_PERMISSIONS.CREDIT_NOTE_CREATE,
        BILLING_PERMISSIONS.CREDIT_NOTE_APPROVE,
        BILLING_PERMISSIONS.DISCOUNT_CREATE,
        BILLING_PERMISSIONS.DISCOUNT_APPROVE,
        BILLING_PERMISSIONS.RECONCILIATION_VIEW,
        BILLING_PERMISSIONS.RECONCILIATION_RECONCILE,
        BILLING_PERMISSIONS.JOURNAL_VOUCHER_CREATE,
        BILLING_PERMISSIONS.JOURNAL_VOUCHER_UPDATE,
        BILLING_PERMISSIONS.JOURNAL_VOUCHER_DELETE,
        BILLING_PERMISSIONS.JOURNAL_VOUCHER_APPROVE,
        BILLING_PERMISSIONS.VENDOR_PAYMENT_CREATE,
        BILLING_PERMISSIONS.VENDOR_PAYMENT_APPROVE,
        BILLING_PERMISSIONS.BUDGET_VIEW,
        BILLING_PERMISSIONS.BUDGET_CREATE,
        BILLING_PERMISSIONS.BUDGET_APPROVE,
        BILLING_PERMISSIONS.REPORT_VIEW,
        BILLING_PERMISSIONS.LEDGER_VIEW,
        BILLING_PERMISSIONS.AUDIT_LOG_VIEW,
        BILLING_PERMISSIONS.DUNNING_VIEW,
        BILLING_PERMISSIONS.DUNNING_RULE_CREATE,
        BILLING_PERMISSIONS.DUNNING_RULE_APPROVE,
        BILLING_PERMISSIONS.DUNNING_WAIVER_CREATE,
        BILLING_PERMISSIONS.DUNNING_REMINDER_SEND,

        BILLING_PERMISSIONS.BILLING_ADVANCE_VIEW_ALL,
        BILLING_PERMISSIONS.BILLING_ADVANCE_VIEW_OWN,
        BILLING_PERMISSIONS.BILLING_ADVANCE_CREATE,
        BILLING_PERMISSIONS.BILLING_ADVANCE_ALLOCATE,
        BILLING_PERMISSIONS.BILLING_ADVANCE_REVERSE_ALLOCATION,
        BILLING_PERMISSIONS.BILLING_ADVANCE_ADJUST,
        BILLING_PERMISSIONS.BILLING_ADVANCE_REFUND,
        BILLING_PERMISSIONS.BILLING_ADVANCE_APPROVE_REFUND,

        BILLING_PERMISSIONS.BILLING_DEPOSIT_VIEW_ALL,
        BILLING_PERMISSIONS.BILLING_DEPOSIT_VIEW_OWN,
        BILLING_PERMISSIONS.BILLING_DEPOSIT_CONFIGURE,
        BILLING_PERMISSIONS.BILLING_DEPOSIT_CREATE,
        BILLING_PERMISSIONS.BILLING_DEPOSIT_ADJUST,
        BILLING_PERMISSIONS.BILLING_DEPOSIT_APPROVE_ADJUSTMENT,
        BILLING_PERMISSIONS.BILLING_DEPOSIT_REFUND,
        BILLING_PERMISSIONS.BILLING_DEPOSIT_APPROVE_REFUND,

        BILLING_PERMISSIONS.ACCOUNTING_LEDGER_VIEW,
        BILLING_PERMISSIONS.ACCOUNTING_TRANSACTION_VIEW,
        BILLING_PERMISSIONS.BANKING_ACCOUNT_VIEW,
        BILLING_PERMISSIONS.REPORTS_BILLING_VIEW,
        BILLING_PERMISSIONS.REPORTS_FINANCIAL_VIEW,
        BILLING_PERMISSIONS.AUDIT_VIEW,
    ],

    // 2. Accountant (accountant)
    [ROLES.ACCOUNTANT]: [
        BILLING_PERMISSIONS.CHARGE_HEAD_VIEW,
        BILLING_PERMISSIONS.CHARGE_HEAD_CREATE,
        BILLING_PERMISSIONS.CHARGE_HEAD_UPDATE,
        BILLING_PERMISSIONS.CONFIG_VIEW,
        BILLING_PERMISSIONS.CONFIG_CREATE,
        BILLING_PERMISSIONS.CONFIG_UPDATE,
        BILLING_PERMISSIONS.INVOICE_VIEW,
        BILLING_PERMISSIONS.INVOICE_GENERATE,
        BILLING_PERMISSIONS.INVOICE_UPDATE,
        BILLING_PERMISSIONS.PAYMENT_VIEW,
        BILLING_PERMISSIONS.PAYMENT_OFFLINE_CREATE,
        BILLING_PERMISSIONS.CREDIT_NOTE_CREATE,
        BILLING_PERMISSIONS.DISCOUNT_CREATE,
        BILLING_PERMISSIONS.RECONCILIATION_VIEW,
        BILLING_PERMISSIONS.RECONCILIATION_RECONCILE,
        BILLING_PERMISSIONS.JOURNAL_VOUCHER_CREATE,
        BILLING_PERMISSIONS.JOURNAL_VOUCHER_UPDATE,
        BILLING_PERMISSIONS.JOURNAL_VOUCHER_DELETE,
        BILLING_PERMISSIONS.VENDOR_PAYMENT_CREATE,
        BILLING_PERMISSIONS.BUDGET_VIEW,
        BILLING_PERMISSIONS.BUDGET_CREATE,
        BILLING_PERMISSIONS.REPORT_VIEW,
        BILLING_PERMISSIONS.LEDGER_VIEW,
        BILLING_PERMISSIONS.AUDIT_LOG_VIEW,
        BILLING_PERMISSIONS.DUNNING_VIEW,
        BILLING_PERMISSIONS.DUNNING_RULE_CREATE,
        BILLING_PERMISSIONS.DUNNING_REMINDER_SEND,

        BILLING_PERMISSIONS.BILLING_ADVANCE_VIEW_ALL,
        BILLING_PERMISSIONS.BILLING_ADVANCE_VIEW_OWN,
        BILLING_PERMISSIONS.BILLING_ADVANCE_CREATE,
        BILLING_PERMISSIONS.BILLING_ADVANCE_ALLOCATE,
        BILLING_PERMISSIONS.BILLING_ADVANCE_REVERSE_ALLOCATION,
        BILLING_PERMISSIONS.BILLING_ADVANCE_ADJUST,
        BILLING_PERMISSIONS.BILLING_ADVANCE_REFUND,

        BILLING_PERMISSIONS.BILLING_DEPOSIT_VIEW_ALL,
        BILLING_PERMISSIONS.BILLING_DEPOSIT_VIEW_OWN,
        BILLING_PERMISSIONS.BILLING_DEPOSIT_CREATE,
        BILLING_PERMISSIONS.BILLING_DEPOSIT_ADJUST,
        BILLING_PERMISSIONS.BILLING_DEPOSIT_REFUND,
        BILLING_PERMISSIONS.BILLING_DEPOSIT_APPROVE_REFUND,

        BILLING_PERMISSIONS.ACCOUNTING_LEDGER_VIEW,
        BILLING_PERMISSIONS.ACCOUNTING_TRANSACTION_VIEW,
        BILLING_PERMISSIONS.BANKING_ACCOUNT_VIEW,
        BILLING_PERMISSIONS.REPORTS_BILLING_VIEW,
        BILLING_PERMISSIONS.REPORTS_FINANCIAL_VIEW,
        BILLING_PERMISSIONS.AUDIT_VIEW,
    ],

    // 3. Resident / Member (resident_owner / resident_tenant / resident)
    [ROLES.RESIDENT_OWNER]: [
        BILLING_PERMISSIONS.OWN_INVOICE_VIEW,
        BILLING_PERMISSIONS.OWN_PAYMENT_CREATE,
        BILLING_PERMISSIONS.OWN_PAYMENT_VIEW,
        BILLING_PERMISSIONS.OWN_LEDGER_VIEW,
        BILLING_PERMISSIONS.BUDGET_VIEW,
        BILLING_PERMISSIONS.BILLING_ADVANCE_VIEW_OWN,
        BILLING_PERMISSIONS.BILLING_DEPOSIT_VIEW_OWN,
    ],

    [ROLES.RESIDENT_TENANT]: [
        BILLING_PERMISSIONS.OWN_INVOICE_VIEW,
        BILLING_PERMISSIONS.OWN_PAYMENT_CREATE,
        BILLING_PERMISSIONS.OWN_PAYMENT_VIEW,
        BILLING_PERMISSIONS.OWN_LEDGER_VIEW,
        BILLING_PERMISSIONS.BUDGET_VIEW,
        BILLING_PERMISSIONS.BILLING_ADVANCE_VIEW_OWN,
        BILLING_PERMISSIONS.BILLING_DEPOSIT_VIEW_OWN,
    ],

    [ROLES.SUPER_ADMIN]: [],
});

module.exports = {
    BILLING_PERMISSIONS,
    BILLING_ROLE_MATRIX,
};
